[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  VITE_SUPABASE_URL = "https://kfjlhujhoooudkhfblon.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmamxodWpob29vdWRraGZibG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2MTUyODMsImV4cCI6MjA5MzE5MTI4M30.ZeNEJbrHYX6aUXpuiSaB1XQXHOAhZ41tdO4k6NmbAz4"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
